Migrate code to 4.4
exo-addons/spaces-administration pull request #10
Opened 2016-11-20 17:16 UTC by boubaker

2018-01-18 20:57 UTC, thomasdelhomenie requested changes
@rdenarie @boubaker I added some little comments, but the main thing missing here is an upgrade plugin to move data from JCR to new Settings storage IMO. Do you think it is worth it ?

2018-01-18 20:57 UTC, thomasdelhomenie commented on services/src/main/java/org/exoplatform/addons/spacesadministration/SpacesAdministrationStorage.java
> +  public final static String SETTINGS = "spacesadministrationsettings";
No need to add the "settings" suffix IMO.

2018-01-18 20:57 UTC, thomasdelhomenie commented on services/src/main/java/org/exoplatform/addons/spacesadministration/SpacesAdministrationStorage.java
> +        values += ";" + membershipToAdd;
Is it intended to change the separator ?

2018-01-24 20:08 UTC, thomasdelhomenie commented
I updated the PR by considering the feedbacks and adding a migration service to move data from JCR to new Settings AI.

2018-01-25 09:24 UTC, rdenarie commented
Ok for me. Tested from 4.4.3 to 4.4.4

2018-01-25 10:08 UTC, thomasdelhomenie commented
OK thanks. I will merge the PR.

2018-01-25 10:08 UTC, thomasdelhomenie approved these changes

2018-01-25 10:09 UTC, merged